name: 'Upload Artifact'
description: 'Uploads a file as an artifact'
inputs:
  name:
    description: 'Name of the artifact'
    required: true
  path:
    description: 'File or directory path to upload'
    required: true
runs:
  using: 'composite'
  shell: bash
  steps:
    - name: Upload Artifact
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.name }}
        path: ${{ inputs.path }}
