- name: Create Pull Request with Label using hub-pr-creator
  uses: JMShadbury/github-actions-library/hub-pr-creator@v1
  with:
    base_branch: 'main'
    head_branch: 'update-branch-${{ github.run_number }}'
    pr_title: 'Update round number to ${{ env.ROUND_NUMBER }}'
    labels: 'automerge'
    github_token: ${{ secrets.GH_PAT }}
