name: 'Pylint Action'
description: 'An action to analyze Python code using pylint.'

author: 'Your Name <your-email@example.com>'
branding:
  icon: 'code'
  color: 'blue'

inputs:
  python-version:
    description: 'The Python version to use.'
    required: true
    default: '3.11'

runs:
  using: 'composite'
  shell: bash
  steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip install -r requirements.txt

    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py') > pylint_output.txt
