name: 'Pylint Action'
description: 'An action to analyze Python code using pylint.'

author: 'Joel Shadbolt <joelshadbolt123@hotmail.com>'
branding:
  icon: 'code'
  color: 'green'

inputs:
  python-version:
    description: 'The Python version to use.'
    required: true
    default: '3.11'

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip install -r requirements.txt

    - name: Analysing the code with pylint
      shell: bash
      run: |
        pylint $(git ls-files '*.py') --disable=C0413,E0401,C0303,C0301,W0621,W1514,C0411,C0115,C0116,R1705,C0115,W0718,C0103,R0801 > pylint_output.txt || PYLINT_STATUS=$?
        cat pylint_output.txt
        if [ ! -z "${PYLINT_STATUS}" ]; then
          exit $PYLINT_STATUS
        fi
