name: Refresh Release

on:
  push:
    branches:
      - main

jobs:
  refresh-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config --global user.name 'Your Name'
        git config --global user.email 'your-email@example.com'

    - name: Delete existing tag
      run: |
        git push --delete origin v1
        git tag --delete v1

    - name: Create new tag
      run: |
        git tag v1
        git push origin v1

    - name: Delete existing release
      uses: actions/delete-release@v1
      with:
        api_token: ${{ secrets.GITHUB_TOKEN }}
        tag: v1

    - name: Create new release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v1
        release_name: Release v1
        draft: false
        prerelease: false
