name: Refresh Release

on:
  push:
    branches:
      - main

jobs:
  refresh-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Delete existing tag
      run: |
        git push --delete origin v1
        git tag --delete v1

    - name: Create new tag
      run: |
        git tag v1
        git push origin v1

    - name: Delete existing release
      run: |
        RELEASE_ID=$(curl -X GET -H "Accept: application/vnd.github.v3+json" -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/${{ github.repository }}/releases/tags/v1 | jq '.id')
        if [ "$RELEASE_ID" != "null" ]; then
          curl -X DELETE -H "Accept: application/vnd.github.v3+json" -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/${{ github.repository }}/releases/$RELEASE_ID
        fi

    - name: Create new release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v1
        release_name: Release v1
        draft: false
        prerelease: false
