name: 'Delete Release'
description: 'Delete a GitHub Release'
inputs:
   github_token:
     description: 'GitHub token'
     required: true
   repository:
     description: 'Repository name'
     required: true
   tag:
     description: 'Tag of the release to delete'
     required: true

runs:
  using: "composite"
  steps:
    - run: .github/scripts/delete-release.sh ${{ inputs.github_token }} ${{ inputs.repository }} ${{ inputs.tag }}
      shell: bash
